### ISSUE TITLE
Problemi su Mac: non tira sù il webserver

### ISSUE THREAD

**Issue by pierol** [valeriopisapia/webpackstarterkit#1]
Ciao Valerio, ti scrivo qui. Ho incontrato problemi du Mac con nodejs 7.2.1 ... npm start non tira sù il webserver:

` webpackstarterkit@1.0.0 start /Users/piero/webpackstarterkit
> PROD_ENV=0 webpack --watch

Starting to optimize CSS...
Processing style.css...
Processed style.css, before: 286, after: 173, ratio: 60.49%
Hash: 9082b103c7e93a85f9d8
Version: webpack 1.14.0
Time: 1328ms
                            Asset       Size  Chunks             Chunk Names
                         build.js    2.28 kB       0  [emitted]  build
                        vendor.js    1.57 kB       1  [emitted]  vendor
                        style.css  173 bytes       0  [emitted]  build
                     build.js.map    2.89 kB       0  [emitted]  build
                    style.css.map    1.07 kB       0  [emitted]  build
                    vendor.js.map    1.63 kB       1  [emitted]  vendor
assets/images/what-is-webpack.png    0 bytes          [emitted]  
                       index.html  387 bytes          [emitted]  
   [2] ./src ^\.\/.*\.html 160 bytes {0} [built]
    + 3 hidden modules

WARNING in ./src/app.js
jshint results in errors
  Use the function form of "use strict". @ line 1 char 1
    "use strict";

  'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). @ line 6 char 1
    let checkName= (firstName, lastName) => {

  'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6'). @ line 6 char 36
    let checkName= (firstName, lastName) => {

  Missing semicolon. @ line 12 char 2
    }

  'console' is not defined. @ line 8 char 9
            console.log('You are not Valerio Pisapia');

  'console' is not defined. @ line 10 char 9
            console.log('You are Valerio Pisapia');

WARNING in ./src/vendor.js
jshint results in errors
  Use the function form of "use strict". @ line 1 char 1
    "use strict";
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
    
    WARNING in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./~/jshint-loader!./src/assets/scss/style.scss
    jshint results in errors
      Unexpected '@'. @ line 1 char 1
        @import "/styles/header";
    
      Unexpected '@'. @ line 2 char 1
        @import "/styles/home";
    
      Expected an assignment or function call and instead saw an expression. @ line 4 char 1
        body{
    
      Missing semicolon. @ line 4 char 5
        body{
    
      Label 'background' on red statement. @ line 5 char 17
        	background: red;
    
      Expected an assignment or function call and instead saw an expression. @ line 5 char 17
        	background: red;
    
      Expected an assignment or function call and instead saw an expression. @ line 7 char 5
        	h1{
    
      Missing semicolon. @ line 7 char 7
        	h1{
    
      Expected an assignment or function call and instead saw an expression. @ line 8 char 14
        		font-family: 'Verdana';
    
      Missing semicolon. @ line 8 char 20
        		font-family: 'Verdana';
    
      Expected '}' to match '{' from line 7 and instead saw ':'. @ line 8 char 20
        		font-family: 'Verdana';
    
      Expected an assignment or function call and instead saw an expression. @ line 8 char 22
        		font-family: 'Verdana';
    
      Expected an assignment or function call and instead saw an expression. @ line 11 char 5
        	img {
    
      Missing semicolon. @ line 11 char 8
        	img {
    
      Unexpected '5'. @ line 12 char 16
        		width: 500px;
    
      Label 'width' on } statement. @ line 13 char 5
        	}
    
      Expected an identifier and instead saw '}'. @ line 13 char 5
        	}
    
      Expected an assignment or function call and instead saw an expression. @ line 13 char 5
        	}
    
      Missing semicolon. @ line 13 char 6
        	}

**Comment by valeriopisapia** [comment]
Fixed.
